### ISSUE TITLE
Option Spread

### ISSUE THREAD

**Issue by sdmiami** [mstrum/robinhood-python#27]
Thanks for putting such great work Matt. I was wondering if you have plans to add buying call/put spread ?

**Comment by sdmiami** [comment]
If you have spread option in portfolio or queue many script will failed. 
Example:
Traceback (most recent call last):
  File "show_pending_options_orders.py", line 77, in <module>
    display_pending_options_orders()
  File "show_pending_options_orders.py", line 22, in display_pending_options_orders
    orders = client.get_options_orders()
  File "/X/X/robinhood-python/robinhood/RobinhoodClient.py", line 2521, in get_options_orders
    assert not response_json['next']
AssertionError

**Comment by mstrum** [comment]
Thanks!  No, I haven't really touched options very much yet, but I do accept pull requests if anyone wants to add it~
