### ISSUE TITLE
BadRequest: {'position_effect': "You can't sell to open an option that you already have a long position in."}

### ISSUE THREAD

**Issue by klepsydra** [mstrum/robinhood-python#33]
Let's say an account already owns an option.  Then I try to sell it:

`python3 ./order_options.py limit sell SQQQ 2019-06-21 10 put 1.0 0.40
`

  
But:  

```
!!!!!!!!!!!!!!!!!! CAUTION !!!!!!!!!!!!!!!!!!
Are you sure that you want to limit sell 1 2019-06-21 $10.00 put options of SQQQ (ProShares UltraPro Short QQQ) for $0.40 each? [N/y]? 
Traceback (most recent call last):
  File "/home/master/www/robinhood-python/robinhood/RobinhoodClient.py", line 50, in _raise_on_error
    response.raise_for_status()
  File "/home/master/.local/lib/python3.5/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.robinhood.com/options/orders/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./order_options.py", line 95, in <module>
    args.price
  File "./order_options.py", line 72, in place_order
    options_instrument['id'], order_type, ORDER_SIDE_TO_DIRECTION[order_side], quantity, price, use_account_url=account_url)
  File "/home/master/www/robinhood-python/robinhood/RobinhoodClient.py", line 2964, in order_options
    _raise_on_error(response)
  File "/home/master/www/robinhood-python/robinhood/RobinhoodClient.py", line 55, in _raise_on_error
    raise BadRequest(http_error.response.json())
robinhood.exceptions.BadRequest: {'position_effect': "You can't sell to open an option that you already have a long position in."}

```

It seems **robinhood/RobinhoodClient.py** has this hard-coded somewhere around line 2948:
` 'position_effect': 'open',`

However, I am unsure how/where to fix this code.  Should you make **position_effect** an optional user parameter?   

Or maybe could you add code to retry with a value of 'close' when the default 'open' fails with this specific error response?

**Comment by klepsydra** [comment]
In the end, I fixed this bug (inability to close option positions) as well as exposed the missing parameters feature (namely time_in_force gfd/gtc) to the user, in my own fork at https://gitlab.com/klepsydra/robinhood-python/commit/0f02a215640bbcec96d8efb6b547376d8eef7c9a

I don't know how to make a pull request since it's on Gitlab.com.  Besides, it's messy code.  I didn't really know how to write it properly, most of the time.  Python is a foreign language to me.
