### ISSUE TITLE
robinhood.exceptions.BadRequest: {'currency_pair_id': ['This field is required.'], 'price': ['This field is required.'], 'quantity': ['This field is required.'], 'ref_id': ['This field is required.'], 'side': ['This field is required.'], 'time_in_for ce': ['This field is required.'], 'type': ['This field is required.']}

### ISSUE THREAD

**Issue by rwburke2** [mstrum/robinhood-python#35]
Hello - - awesome library - - thanks for doing it.  I installed, modified the auth, and when trying to trade a crypto, I get the following error - - I've been looking through the code to see what the issue may be, but thought I'd put it up here too.  Best

Traceback (most recent call last):
  File "order_crypto.py", line 72, in <module>
    args.price
  File "order_crypto.py", line 55, in place_order
    currency_pair_id, order_type, order_side, quantity, price)
  File "/home/ubuntu/projects/robinhood-python/robinhood/RobinhoodClient.py", line 2419, in order_crypto
    _raise_on_error(response)
  File "/home/ubuntu/projects/robinhood-python/robinhood/RobinhoodClient.py", line 55, in _raise_on_error
    raise BadRequest(http_error.response.json())
robinhood.exceptions.BadRequest: {'currency_pair_id': ['This field is required.'], 'price': ['This field is required.'], 'quantity': ['This field is required.'], 'ref_id': ['This field is required.'], 'side': ['This field is required.'], 'time_in_for
ce': ['This field is required.'], 'type': ['This field is required.']}

**Comment by rwburke2** [comment]
figured it out
